### ISSUE TITLE
Using external Boost to build Jinja2Cpp instead of internal submodule

### ISSUE THREAD

**Issue by DragonOsman** [jinja2cpp/Jinja2Cpp#113]
I want to build the library again, but when I tried I found this in the output message:
```
-- 'internal' dependencies mode selected for Jinja2Cpp. All dependencies are used as submodules
```
This worries me.  I'm okay with it using the internal submodule for `expected-lite`, `variant-lite` and etc., but I want it to use my own Boost instead of the one in the submodule.  Is it possible to do this?  Or do I have to get all of the stuff myself for that and not just Boost?  And if I specify the path to Boost and have `internal` defined, will it ignore that and use the internal submodule for Boost?

**Comment by flexferrum** [comment]
>  Is it possible to do this?
Yes. And now it's a little bit easier. You have to specify `-DJINJA2CPP_DEPS_MODE=external-boost` and build script will try to find `boost` outside of the package. See samples here:
https://github.com/jinja2cpp/examples-build/tree/master/external/external_boost
and here:
https://github.com/jinja2cpp/examples-build/tree/master/subproject/external_boost

**Comment by DragonOsman** [comment]
Thanks for the reply and those references and info.
