### ISSUE TITLE
Getting Error On `tpl.RenderAsString(params).size()` - Please Help

### ISSUE THREAD

**Issue by DragonOsman** [jinja2cpp/Jinja2Cpp#116]
I have an error coming from this part in my currency converter server app code:
```cpp
else if (req.target() == "/")
{
	jinja2::Template tpl;
	tpl.LoadFromFile(path.c_str());
	jinja2::ValuesMap params = { { "googlekey", std::string(googlekey) } };

	http::response<http::string_body> res{
		std::piecewise_construct,
		std::make_tuple(tpl.RenderAsString(params)),
		std::make_tuple(http::status::ok, req.version()) };
	res.set(http::field::server, BOOST_BEAST_VERSION_STRING);
	res.set(http::field::content_type, "text/html");
	res.set(http::field::content_length, tpl.RenderAsString(params).size());
	res.set(http::field::access_control_allow_origin, "https://www.osmanzakir.dynu.net");
	res.keep_alive(req.keep_alive());
	return send(std::move(res));
}
```
The error is:
```
1>e:\programming\visual_studio_2019\projects\currency_converter\currency_converter\currency_converter.cpp(505): error C2039: 'size': is not a member of 'nonstd::expected_lite::expected<std::string,jinja2::ErrorInfoTpl<char>>'
```
It's coming from this line:
```cpp
res.set(http::field::content_length, tpl.RenderAsString(params).size());
```
Was something changed about this in the new version or something?  Any help is appreciated.  Thanks.

I'm using VS2019 with the VS2017 toolset, and C++17 settings, with static runtime.

**Comment by flexferrum** [comment]
Yes, see the changelog ( https://github.com/jinja2cpp/Jinja2Cpp#breaking-changes )
> `RenderAsString` method now returns `nonstd::expected` instead of regular `std::string`

So it's possible to get render-time dagnostics.

**Comment by DragonOsman** [comment]
Thanks for the reply.

**Comment by DragonOsman** [comment]
I tried to do it like this:
```cpp
auto render_result = tpl.RenderAsString(params);
if (!render_result)
{
	return send(server_error(render_result.error()));
}
auto &content = render_result.value();
```
But I got an error that basically tells me that the `send` function expects a `boost::string_view` (here, treated as a `boost::beast::string_view`).  How can I return the error information as a string_view or at least a std::string?

**Comment by flexferrum** [comment]
You can do something like this: https://github.com/jinja2cpp/Jinja2Cpp/blob/504b8a5bdd45c028da076c76a7c29270438e5dab/test/errors_test.cpp#L14

```c++
std::string ErrorToString(const jinja2::ErrorInfo& error)
{
    std::ostringstream errorDescr;
    errorDescr << error;
    return errorDescr.str();
}
```

**Comment by DragonOsman** [comment]
Yeah, it works now.  Thanks for the help.
