### ISSUE TITLE
Bad git hash for nonstd/value-ptr-lite

### ISSUE THREAD

**Issue by satarsa** [jinja2cpp/Jinja2Cpp#121]
I cannot build Jinja2C++ tag 0.9.2 anymore because of:

`error: Server does not allow request for unadvertised object 2fd703f8a8e6a6b0bd210f12313d4f18530ff0c3
Fetched in submodule path 'thirdparty/nonstd/value-ptr-lite', but it did not contain 2fd703f8a8e6a6b0bd210f12313d4f18530ff0c3. Direct fetching of that commit failed.
CMake Error at thirdparty/internal_deps.cmake:14 (add_library):
  add_library cannot create ALIAS target "value-ptr-lite" because target
  "value-ptr-lite" does not already exist.
`

I guess something happened involving git rebase :)

**Comment by flexferrum** [comment]
Thanks for pointing that out. Will try to fix it.

**Comment by flexferrum** [comment]
Please, try now. Everything should be fine.

**Comment by satarsa** [comment]
Yes, it is working now, but I had to completely re-clone the repo.
Thanks!

**Comment by flexferrum** [comment]
Perfect!
