### ISSUE TITLE
Implement 'slice' filter

### ISSUE THREAD

**Issue by flexferrum** [jinja2cpp/Jinja2Cpp#141]
Implement `slice` filter according the [jinja2 documentation](https://jinja.palletsprojects.com/en/2.10.x/templates/#slice):

> Slice an iterator and return a list of lists containing those items.
If you pass it a second argument it’s used to fill missing values on the last iteration.

For instance, `slice(3, 0)` applied to the list `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]` should give the list of lists of three items each:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [10, 11, 12],
 [13, 14, 15],
 [16, 0, 0]]
```

**Comment by gupta409** [comment]
I can do this. Please feel free to assign.

**Comment by flexferrum** [comment]
> I can do this. Please feel free to assign.

Thanks a lot!

**Comment by flexferrum** [comment]
One notice before the implementation. There are two type of lists in the Jinja2C++ engine: which supports indexing and which doesn't (generator-based lists, lists over the forward-only iterators etc.). For lists with indexing available it's possible to use generators to produce slicing. For lists without indexing it's better to make a sliced copy of the original list.
