### ISSUE TITLE
Implement 'tojson' filter

### ISSUE THREAD

**Issue by flexferrum** [jinja2cpp/Jinja2Cpp#142]
Implement 'tojson' filter according to the [jinja2 specification](https://jinja.palletsprojects.com/en/2.10.x/templates/#tojson):

> Dumps a structure to JSON so that it’s safe to use in <script> tags. It accepts the same arguments and returns a JSON string. Note that this is available in templates through the |tojson filter which will also mark the result as safe. Due to how this function escapes certain characters this is safe even if used outside of <script> tags.
>
> The following characters are escaped in strings:
> - <
> - &gt;
> - &
> - '
>
> This makes it safe to embed such strings in any place in HTML with the notable exception of double quoted attributes. In that case single quote your attributes or HTML escape it in addition.
>
> The indent parameter can be used to enable pretty printing. Set it to the number of spaces that the structures should be indented with.

**Comment by vvish** [comment]
Hi! Could you please assign the task on me.

**Comment by flexferrum** [comment]
Sure!
