### ISSUE TITLE
Implement 'xmlattr' filter

### ISSUE THREAD

**Issue by flexferrum** [jinja2cpp/Jinja2Cpp#143]
Implement 'xmlattr' filter according to the [jinja2 specification](https://jinja.palletsprojects.com/en/2.10.x/templates/#xmlattr):

> Create an SGML/XML attribute string based on the items in a dict. All values that are neither none nor undefined are automatically escaped:
> 
```
<ul{{ {'class': 'my_list', 'missing': none,
        'id': 'list-%d'|format(variable)}|xmlattr }}>
...
</ul>
```

> Results in something like this:
```
<ul class="my_list" id="list-42">
...
</ul>
```

> As you can see it automatically prepends a space in front of the item if the filter returned something unless the second parameter is false.

**Comment by vvish** [comment]
Please assign this task on me
