### ISSUE TITLE
Implement 'format' filter

### ISSUE THREAD

**Issue by flexferrum** [jinja2cpp/Jinja2Cpp#145]
Implement 'format' filter according to the [jinja2 specification](https://jinja.palletsprojects.com/en/2.10.x/templates/#format):

> Apply python string formatting on an object:
```
{{ "%s - %s"|format("Hello?", "Foo!") }}
    -> Hello? - Foo!
```

Actually, {fmt} library has got all necessary facilities for analyze python format strings so, it could be good idea to reuse this facilities during resolving this issue.

**Comment by mateka** [comment]
I would like to try do it! :)

**Comment by flexferrum** [comment]
You're welcome!

**Comment by mateka** [comment]
I have looked into this during weekend, and there are three options:
1. using format internals
2. limiting number of format params
3. creating new format library. 
It is because it is not possible to "unpack"  dynamic vector into static variadic args.

**Comment by flexferrum** [comment]
I supposed to follow option 1. I. e. use format internals. We're able to stick to the particular version of {fmt} (i. e. 6.0) and use it's facilities:
1. Format string parser: https://github.com/fmtlib/fmt/blob/b615eca9641f12edb6713058437fd8e83c03fe09/include/fmt/format.h#L2433
2. Variable number of arguments storage: https://github.com/fmtlib/fmt/blob/e9b9b0aefaf3dacf8554ba93bd404248574945ed/include/fmt/core.h#L1189
