### ISSUE TITLE
Implement 'raw/endraw' statement

### ISSUE THREAD

**Issue by flexferrum** [jinja2cpp/Jinja2Cpp#146]
Implement 'raw/endraw' statement according to [Jinja2 documentation](https://jinja.palletsprojects.com/en/2.10.x/templates/#escaping):

> For bigger sections, it makes sense to mark a block raw. For example, to include example Jinja syntax in a template, you can use this snippet:
```
{% raw %}
    <ul>
    {% for item in seq %}
        <li>{{ item }}</li>
    {% endfor %}
    </ul>
{% endraw %}
```

I. e. everything between `raw`/`endraw` tags should be copied to the destination string as-is, without any interpretation.

**Comment by morenol** [comment]
Which would be the best approach?
Handle them as a Statement? or create a new regex for them and handle them at their own way in ParseRoughMatch?

**Comment by flexferrum** [comment]
I'm considering the second option. I. e. do it in ParseRoughMatch, similar comments handling.

**Comment by morenol** [comment]
Ok, I will try that. I think that is the way it is implemented in the python version
