### ISSUE TITLE
CMake issue

### ISSUE THREAD

**Issue by manuka89** [jinja2cpp/Jinja2Cpp#154]
Hi,

I would like to use your library but I have a CMake issue. I've succesfully checked out the branch release_1.0.0 and then I executed git submodule update --init --recursive to retrieve the submodules. Then I followed the instructuions in the readme file and I received the following errors:

`-- 'external' dependencies mode selected for Jinja2Cpp. All dependencies are treated as external
CMake Warning at thirdparty/thirdparty-external.cmake:23 (find_package):
  By not providing "Findexpected-lite.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "expected-lite", but CMake did not find one.

  Could not find a package configuration file provided by "expected-lite"
  with any of the following names:

    expected-liteConfig.cmake
    expected-lite-config.cmake

  Add the installation prefix of "expected-lite" to CMAKE_PREFIX_PATH or set
  "expected-lite_DIR" to a directory containing one of the above files.  If
  "expected-lite" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  thirdparty/thirdparty-external.cmake:37 (find_hdr_package)
  thirdparty/CMakeLists.txt:43 (include)
  CMakeLists.txt:150 (include)

-- Could NOT find expected-lite (missing: expected-lite_INCLUDE_DIR) 
CMake Error at thirdparty/thirdparty-external.cmake:33 (message):
  expected-lite not found!
Call Stack (most recent call first):
  thirdparty/thirdparty-external.cmake:37 (find_hdr_package)
  thirdparty/CMakeLists.txt:43 (include)
  CMakeLists.txt:150 (include)
-- Configuring incomplete, errors occurred!`

Could you please advise?

Thank you in advance.

**Comment by flexferrum** [comment]
Thank you for the interest for the project.

First of all, look at this chapter: https://jinja2cpp.dev/docs/build_and_install.html#additional-cmake-build-flags There is description of different dependency management modes supported by Jinja2C++ CMake (variable `JINJA2CPP_DEPS_MODE`). Particularly `external` mode means that you provide all dependencies externally. This mode is default for the release branches (and archives).

So, you problem has got two possible solutions:
1. Define `JINJA2CPP_DEPS_MODE` var for CMake run as  `internal`. In this case all dependencies will be taken from the submodules (as you expect). This is the most simple way.
2. Follow this sample: https://github.com/jinja2cpp/examples-build/tree/master/subproject/external There are sample CMake and run scripts for `external` deps management mode.

**Comment by manuka89** [comment]
Thank you for your fast reply. I'm sorry, I have not seen this flag. After having added it to the compilation it works fine. Thanks!

In order to integrate the Jinja2Cpp to my project I've wrote a CMakeLists.txt following the description at: https://jinja2cpp.dev/docs/build_and_install.html

Here is my CMakeLists.txt:
`cmake_minimum_required (VERSION 3.0)
project (jinja_test)
list(APPEND CMAKE_MODULE_PATH ${JINJA2CPP_INSTALL_DIR}/lib64/jinja2cpp)
find_package(jinja2cpp)
include_directories(${JINJA2CPP_INCLUDE_DIR})
message(STATUS "Include directory: " ${JINJA2CPP_INCLUDE_DIR})
add_executable(jinja_test test.cpp)
target_link_libraries(jinja_test ${JINJA2CPP_LIBRARY})`

And here is the result of the execution:
cmake .. -DJINJA2CPP_INSTALL_DIR=.
-- Include directory: 
-- Configuring done
-- Generating done
-- Build files have been written to: .

Could you please tell me why the include directory is empty even though it founds Jinja?

**Comment by flexferrum** [comment]
Actually, I need to check, but I suppose (according to this file: https://github.com/jinja2cpp/Jinja2Cpp/blob/master/cmake/public/jinja2cpp-config.cmake.in ) public INCLUDE_DIR (and necessary defines) for Jinja2Cpp provided as a target property, not as a global variable. See this issue: https://github.com/jinja2cpp/Jinja2Cpp/issues/95

How it works: you provide the path to the jinja2cpp installation to the CMake (via **CMAKE_PREFIX_PATH,** not **MODULE**), during the configuration step CMake locates the jinja2cpp-config.cmake file and then CMake adds jinja2cpp target to the list of targets as if jinja2cpp is a subproject of your project. So, finally, you can freely link with jinja2cpp without any other additions.

**Comment by manuka89** [comment]
Thanks, it works, just needed to add pthread to link libraries.
