### ISSUE TITLE
Incompatibility with expected-lite library

### ISSUE THREAD

**Issue by jpcima** [jinja2cpp/Jinja2Cpp#157]
Hi, when using an external checkout of `expected-lite`, the build fails.
Using Linux g++ and clang++.

The version pointed by the submodule works, it starts failing following this commit (included).
https://github.com/martinmoene/expected-lite/commit/9c58fdb91908ee10289fd4e504b970e2669739ad

The compiler reports:
```
In file included from thirdparty/jinja2cpp/src/statements.cpp:1:
In file included from thirdparty/jinja2cpp/src/expression_evaluator.h:4:
In file included from thirdparty/jinja2cpp/src/internal_value.h:4:
In file included from thirdparty/jinja2cpp/include/jinja2cpp/value.h:7:
thirdparty/variant-lite/include/nonstd/variant.hpp:1915:18: error: call to implicitly-deleted copy constructor of 'nonstd::expected<std::shared_ptr<TemplateImpl<char> >, ErrorInfoTpl<char> >'
        return v(arg);
                 ^~~
```

**Comment by flexferrum** [comment]
That's why I stick to the particular versions of third-parties. Thanks, I'll check this out.

**Comment by flexferrum** [comment]
What compiler and settings do you use?

**Comment by flexferrum** [comment]
Looks like a bug in nonstd::expected-lite (template ctor isn't a valid form of copy ctor declaration). Will investigate further with @martinmoene

**Comment by jpcima** [comment]
Thanks for the effort to identify the origin of the trouble.
For the time being, I'm remaining on the older version myself; I thought it was a thing worth reporting regardless.

The problem is reproduced by updating the submodule, and running the cmake build without anything particular.

>What compiler and settings do you use?

- gcc version 9.1.0 (GCC)
- clang version 8.0.1 (tags/RELEASE_801/final)

both failing with about identical errors.

For GCC specifically, I've to make some adjustments to warning flags.
It doesn't recognize `-Wno-unused-command-line-argument`, and since `-Werror` is also on, this flag combination fails the build.

**Comment by flexferrum** [comment]
> For the time being, I'm remaining on the older version myself; I thought it was a thing worth reporting regardless.

Yes, sure. Thanks for pointing that out.

> both failing with about identical errors.

But MSVC isn't. That's why I asked.

> It doesn't recognize -Wno-unused-command-line-argument, and since -Werror is also on, this flag combination fails the build.

Thanks. I'll add it to the upstream.
