### ISSUE TITLE
Repeat string implementation

### ISSUE THREAD

**Issue by morenol** [jinja2cpp/Jinja2Cpp#158]
Looking into the jinja2 [reference](https://jinja.palletsprojects.com/en/2.10.x/templates/#math) and into the jinja2cpp code, I noticed that this is not implemented

> \* Multiply the left operand with the right one. {{ 2 * 2 }} would return 4. This can also be used to repeat a string multiple times. {{ '=' * 80 }} would print a bar of 80 equal signs.

Can I implement that?

**Comment by flexferrum** [comment]
Yes!
