### ISSUE TITLE
Difference of LstripBlocks behavior with Jinja2

### ISSUE THREAD

**Issue by jpcima** [jinja2cpp/Jinja2Cpp#159]
Hi, I notice that Jinja2Cpp and Jinja2 print different results using this template.
The settings `trimBlocks` and `lstripBlocks` are set to true in both cases.

```
{% for i in range(1) %}
   i = {{i}}
{% endfor %}
```

From Jinja2: `i = 0`
From Jinja2Cpp: `i =0`

It raises the question: are `{{}}` supposed to be affected by lstripBlocks?
Remark: it becomes identical if I substitute `{{+i}}` instead of `{{i}}`

The reference python code:
```
#!/usr/bin/env python
import sys
from jinja2 import Environment, FileSystemLoader
env = Environment(
    loader=FileSystemLoader('.'),
    lstrip_blocks=True, trim_blocks=True
)
template = env.get_template(sys.argv[1])
print(template.render())
```

using Jinja 2.10.3

**Comment by flexferrum** [comment]
Thanks! Seems like I missed this part of the Jinja2 lstrip_blocks description:

> The lstrip_blocks option can also be set to strip tabs and spaces from the beginning of a line to the start of a block. (Nothing will be stripped if there are other characters before the start of the block.)

Or there was not such addition when I read the Jinja2 docs before.

**Comment by jpcima** [comment]
Comparing with Jinja2 output, I don't think it's the case at all that space leading to expressions must be eliminated.

For example, rendering this template retains the space which precedes the `{{w}}` expression.
However, it is eliminated before the comment block `{##}`.
```
switch (index) {
{% for w in ["foo","bar"] %}
case {{loop.index0}}:
    {{w}} = value; break;
    {#my comment#}/*something*/
{% endfor %}
}
```

Result
```
switch (index) {
case 0:
    foo = value; break;
/*something*/
case 1:
    bar = value; break;
/*something*/
}
```

**Comment by flexferrum** [comment]
I'll check it.

**Comment by flexferrum** [comment]
Actually, that's not the easy Jinja2 specs part to implement. There is documented (expected) behavior and implemented. https://github.com/pallets/jinja/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+trim+

**Comment by flexferrum** [comment]
> 
> 
> What might be a fix, it has resolved the simplest cases.
> [jpcima@9110b93](https://github.com/jpcima/Jinja2Cpp/commit/9110b93112b1ba270b1ed1c95fccaf53519b7b14)
> It also breaks the unit tests, which I believe are wrong in the assumption of how `block` operates.
> 
> Trying to get unit tests matching python, I think I encountered another defect.
> 
>     * [ ]  the library strips newline after `{% set %}` statements
> 
> 
> Example (`FooBar` vs `Foo\nBar`)
> 
> ```
> Foo{%set testVal='first entry' %}
> Bar
> ```

https://github.com/jinja2cpp/Jinja2Cpp/issues/161#issuecomment-539913312

**Comment by flexferrum** [comment]
Investigation of the python Jinja2 behavior shown that `lstrip_blocks`/`trim_blocks` affect only tags and comments, but not expressions.

**Comment by jpcima** [comment]
I came to the identical conclusion, yes.

Do you think it would be a find idea to integrate optionally jinja2 into the test suite, in order to automate this comparison?
(and the bonus of being able to check trim/lstrip settings in accordance)

**Comment by flexferrum** [comment]
> Do you think it would be a find idea to integrate optionally jinja2 into the test suite, in order to automate this comparison?

I was considering this idea but still find no way to do the smooth integration. For this particular case I already have made the test samples with different style of default trimming and added them to the Jinja2C++ tests. Have found a lot of bugs.

**Comment by jpcima** [comment]
>I was considering this idea but still find no way to do the smooth integration.

It's invocable as a script into an external python interpreter process.
Is there a particular inconvenient about using this method?
I don't mind to implement it.

**Comment by flexferrum** [comment]
As an alternative is to do integration with python via the boost.python. It can be faster (from the execution time prospective)

**Comment by flexferrum** [comment]
The fix is ready.
