### ISSUE TITLE
In a base template, {% block %} contents not rendered

### ISSUE THREAD

**Issue by jpcima** [jinja2cpp/Jinja2Cpp#161]
Hi, I believe there is rendering trouble with `block` functionality.
It's when this simple template is rendered: `A{% block foo %}B{% endblock %}`

Jinja result: `AB`
Jinja2Cpp: `A`

**Comment by jpcima** [comment]
What might be a fix, it has resolved the simplest cases.
https://github.com/jpcima/Jinja2Cpp/commit/9110b93112b1ba270b1ed1c95fccaf53519b7b14
It also breaks the unit tests, which I believe are wrong in the assumption of how `block` operates.

Trying to get unit tests matching python, I think I encountered another defect.
- [ ] the library strips newline after `{% set %}` statements

Example (`FooBar` vs `Foo\nBar`)
```
Foo{%set testVal='first entry' %}
Bar
```

**Comment by flexferrum** [comment]
Thanks for investigating!

> Trying to get unit tests matching python, I think I encountered another defect.

I'm not sure this is a bug in Jinja2C++:
> In the default configuration:
> - a single trailing newline is stripped if present
> -  other whitespace (spaces, tabs, newlines etc.) is returned unchanged
> If an application configures Jinja to trim_blocks, **the first newline after a template tag** is removed automatically (like in PHP).

So, according to _docs_ first newline char should stripped after the tag, which is mean that `FooBar` seems like a correct output.

**Comment by jpcima** [comment]
>If an application configures Jinja to trim_blocks

Under my test programs, neither c++ or python were configured with `trim_blocks`.
They have it off by default.

When I set it on in python, I get `FooBar` indeed.
C++ doesn't care, it's giving `FooBar` regardless the setting is on or off.

**Comment by flexferrum** [comment]
Thanks! That's significant addition.

**Comment by flexferrum** [comment]
> What might be a fix, it has resolved the simplest cases.
> jpcima@9110b93
> It also breaks the unit tests, which I believe are wrong in the assumption of how block operates.

Yes, this fix looks good.

**Comment by jpcima** [comment]
>Yes, this fix looks good.

In fact, it isn't; it doesn't handle it in an intermediate template of 2 levels inheritance.
Consider the example.

A.txt: `A{% block foo %}B{% endblock %}`
B.txt: `{% extends "A.txt" %}{% block foo %}C{% block bar %}D{% endblock %}{% endblock %}
`
C.txt: `{% extends "B.txt" %}{% block bar %}E{% endblock %}`

Py: `AB`, `ACD`, `ACE`
Cpp: `AB`, `AC`, `ACE`

**Comment by flexferrum** [comment]
Now `block` statement should work as expected.
