### ISSUE TITLE
Global intrinsic functions like `range` not working in child template

### ISSUE THREAD

**Issue by jpcima** [jinja2cpp/Jinja2Cpp#166]
Hi, thanks for great work in the latest commits.
I find there remains an issue after applying the bugfixes.

In a child template, range-for appears non-working.
In the example, the first case is going to print `Foo1,Foo2,Foo3,`; but the same loop in an overriden block outputs nothing.

1.txt
```
{% block A %}
This is original block "A".
{% for i in range(3) %}Foo{{i+1}},{% endfor %}
{% endblock %}
```

2.txt
```
{% extends "1.txt" %}
{% block A %}
This is overriden block "A".
{% for i in range(3) %}Foo{{i+1}},{% endfor %}
{% endblock %}
```

**Comment by flexferrum** [comment]
Hm... You're right. I have to check this out. That's very strange behavior.

**Comment by flexferrum** [comment]
The problem is in visibility of the global functions. If you replace `range(3)` with `[1, 2, 3]` in the second template all will work fine.

**Comment by jpcima** [comment]
Ok, about my personal globals which I insert using `env.AddGlobal`, these are recognized though.

**Comment by jpcima** [comment]
I find something at this call site of `values.Clone()`.
When passing `true` to the function, `range()` is working.
https://github.com/jinja2cpp/Jinja2Cpp/blob/69476050b7d71aa68216cc039e73e7b5159aab45/src/statements.cpp#L268

**Comment by flexferrum** [comment]
BTW, globals should work with any value of this param.

**Comment by jpcima** [comment]
I'm a bit confused about understanding the vocabulary regarding the various scope rules.

I observe that the `range` global is set into `intParams`, or `extValues`/`m_externalScope` as it's known on `RenderContext` side.

When it's cloned, it doesn't pass to the clone context, it's only `m_globalScope` which does, externals are replaced with an empty scope.

Maybe it's `intParams` and `extParams` are swapped at `TemplateImpl::Render`?

**Comment by flexferrum** [comment]
No. I suppose, problem is here: https://github.com/jinja2cpp/Jinja2Cpp/blob/69476050b7d71aa68216cc039e73e7b5159aab45/src/template_impl.h#L190

Globals should set up in `extParams` rather than `intParams`.

**Comment by jpcima** [comment]
This small change fixes the problem on my side, and the test suite passes.
