### ISSUE TITLE
Garbage printed to output when rendering index of reflected std::vector<std::string>

### ISSUE THREAD

**Issue by rlecina** [jinja2cpp/Jinja2Cpp#168]
Hi

I'm getting garbage rendered in the output when accessing an index of a reflected std::vector<std::string>. I've reduced the code and template to this
```
    std::vector<std::string> list = {{"MyVal1"},{"MyVal2"}, {"MyVal3"}};
    jinja2::Template tpl;
    if(auto result = tpl.LoadFromFile("template.txt"))
    {
            jinja2::ValuesMap params = {
              {"list", jinja2::Reflect(list)},
            };
            std::cout << tpl.RenderAsString(params).value() << '\n';
    }
```
And the template
```
{{list[0]}}
```
I've being debugging the library code and I've found that in line 296 of internal_value.cpp the call to ``indexer->GetItemByIndex(idx)`` is creating a temporary jinja2::Value containing an std::string
Then in line 297 of internal_value.cpp InputValueConvertor is returning a jinja2::InternalValue containing a string_view of that std::string contained in the temporary Value
Reflecting on &list to use PtrItemAccessor instead of ValueAccessor has the same behaviour
Not actually sure if it would be better/safer that GetItemByIndex would return an string_view to avoid copies or that the InputValueConvertor wouldn't allow string_views

I was testing with commit 69476050b7d71aa68216cc039e73e7b5159aab45 in Visual Studio 2019  in Debug mode (I was having issues also in RelWithDbgInfo). Library was built with default values got from CMake

**Comment by flexferrum** [comment]
Thanks! I'll check it out!
