### ISSUE TITLE
jinja2::TemplateEnv is thread-safe ?

### ISSUE THREAD

**Issue by linuxpham** [jinja2cpp/Jinja2Cpp#176]
Hi Admin,

**jinja2::TemplateEnv** is thread-safe (multi-threading) ?

Does that mean I cal use it in multi-threading at the same time?

Thanks!

**Comment by flexferrum** [comment]
Yes, it should be safe to use it in multi-thread environment.

**Comment by linuxpham** [comment]
Thanks admin!
