### ISSUE TITLE
Cannot loop some expressions in `for` that Jinja2 can

### ISSUE THREAD

**Issue by jpcima** [jinja2cpp/Jinja2Cpp#180]
Hi, I have tried a set of expressions which are not currently working as expected.

```
1. {% for v in [1, 2] %}{{v}}{% endfor %}
2. {% for v in [1, 2]+[3, 4] %}{{v}}{% endfor %}
3. {% for v in "ab" %}{{v}}{% endfor %}
4. {% for v in "ab"+"cd" %}{{v}}{% endfor %}
5. {% for v in 'a' ~ 'b' %}{{v}}{% endfor %}
```
According to Jinja2:
```
1. 12
2. 1234
3. ab
4. abcd
5. ab
```

In Jinja2cpp, I find only the first one is working, the other 4 evaluate as empty.

I believe that `3` `4` and `5` are because it's not handled to loop over characters.
Regarding `2`, I'm under impression it's the `+` operation not supported for concatenating lists. (possibly in scope of issue #135)

**Comment by flexferrum** [comment]
Hi! Thank you for pointing that out. Actually, you're right. `2` is because of `+` operator doesn't concatenate lists (but it should? ok). `3`, `4`, and `5` need checking. Strings should be treated as iterable (in general). But seems like something went wrong. Will check it soon with #178 issue.

**Comment by jpcima** [comment]
>2 is because of + operator doesn't concatenate lists (but it should? ok).

Yes. Lists also recognize a commutative `*` operator on (List, Int) which repeats N times the sequence.

>Strings should be treated as iterable (in general). But seems like something went wrong.

I'm sure the commented part of `ListConverter` must be relevant to the problem.
https://github.com/jinja2cpp/Jinja2Cpp/blob/78e0a7c1dab7b4b16f52557d5839a752f4cf0b53/src/internal_value.cpp#L166-L170

**Comment by jpcima** [comment]
I confirm this worked great, thanks for the work.
