### ISSUE TITLE
Compilation in C++17 under MinGW on Windows 10

### ISSUE THREAD

**Issue by Alex-Tsvetanov** [jinja2cpp/Jinja2Cpp#185]
I want to compile the library and use it as source. I have no ``CMakeLists.txt`` for my project and I am just using just ``make`` to compile it. 

BUT I'm using C++17 and I'm not able to compile Jinja2Cpp in ``C++17``.

1. Can you provide detailed instructions how to do it?
I tried to put the variable from instruction in the section about ``C++17`` in the ``cmake`` command and ``-D`` parameter and ... nothing.
 
2. Also I'd like to know what ``flags`` should I add to my compile command (for my project I mean) to use all the staff provided by ``Jinja2Cpp``

Thank you in advance. 😄 

P.S.: I'm on ``Windows 10`` and I'm using ``MinGW (8.1.0)`` as C/C++ compiler. I'm also doing the command-line staff (``make/cmake`` commands) under git bash (means I'm using the Linux shell syntax)
P.S.2: I wanted to help you via pull request about how to compile with ``Windows & MinGW`` but I'm so far away from ``CMake`` configs and it was so hard for me to change anything in the configs in a way that has even a small chance to work.

**Comment by flexferrum** [comment]
Hi.
It's difficult what's wrong without any diagnostic from the compiler. Personally I use MinGW 8/Windows 10 as an one of the primary development environment, so, it should work.

**Comment by Alex-Tsvetanov** [comment]
Firstly in the log it is written that cmake will use msvc compiler (which I do not want).
Secondly it is written that the standard that will be used is 14 (which is not 17).

So my question is how to set explicitly MinGW compiler and C++17 standard.

(I will provide some logs later but when I tried to use C++17 there were lines "Unknown standard" (a little bit longer text but that was the meaning))

**Comment by Alex-Tsvetanov** [comment]
![commands](https://user-images.githubusercontent.com/14363901/68749748-6955f480-0607-11ea-8add-64fc630df0aa.png)

[cmake_log.txt](https://github.com/jinja2cpp/Jinja2Cpp/files/3840306/cmake_log.txt)

As you can see:
```
-- The C compiler identification is MSVC 19.23.28107.0
-- The CXX compiler identification is MSVC 19.23.28107.0
```
and my own try to set up c++17:
```
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Failed
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Failed
```
Also there is a warning in the console:
```
CMake Warning (dev) at thirdparty/json/rapid/CMakeLists.txt:12 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Even though I tried:
![commands2](https://user-images.githubusercontent.com/14363901/68750039-e97c5a00-0607-11ea-9c4a-221f4da328d4.png)
and the result was:
[cmkae_build_log.txt](https://github.com/jinja2cpp/Jinja2Cpp/files/3840337/cmkae_build_log.txt)
```
MSBUILD : error MSB1009: Project file does not exist.
```

**Comment by flexferrum** [comment]
Oh, I see... You try to run CMake build without the knowledge how to do it properly. :)
You can investigate this file: https://github.com/jinja2cpp/Jinja2Cpp/blob/master/appveyor.yml It contains all necessary instructions to run Jinja2Cpp build with MinGW. In two words:
1. You should use `Unix Makefiles` generator for run the MinGW build: `-G "Unix Makefiles"
2. Path to MinGW should be in the PATH variable.

Also, you can try to use GUI version of the CMake. In this case it offers you to select the compiler and type of the generator.

Regarding to warning... Unfortunately, it comes from the third-party lib so it's difficult to suppress it.

**Comment by Alex-Tsvetanov** [comment]
[CMakeLists.txt](https://github.com/jinja2cpp/Jinja2Cpp/files/3840452/CMakeLists.txt)
That's the edited by me CMakeLists.txt

**Comment by Alex-Tsvetanov** [comment]
Ok, I will try tonight and will either close the issue or continue with my stupid questions generated by my lake of knowledge in CMake 😄

**Comment by flexferrum** [comment]
Also, you can be interested in this sample: https://github.com/jinja2cpp/examples-boost.beast

**Comment by Alex-Tsvetanov** [comment]
Actually I want to integrate Jinja2Cpp in my framework - [look at this example](https://github.com/Alex-Tsvetanov/WebFrame/blob/master/src/main.cpp).

**Comment by flexferrum** [comment]
Wow! BTW, I think, this sample can help you to design templates hierarchy properly.

**Comment by Alex-Tsvetanov** [comment]
Ok. I did:
```
cd Jinja2Cpp
mkdir build
cd build
cmake ../ -G"Unix Makefiles" # successful
```
then
```
make
```

And I ran 
```
$ ./jinja2cpp_tests.exe; echo $?
127
```

Even though It is created ``libjinja2cpp.a``. So how should I link it and run successfully the tests of the library so that I will be sure that I've compiled everything correctly. @flexferrum?

**Comment by flexferrum** [comment]
Have you provided all necessary paths to MinGW binaries/libs?

Also, it's better to perform install step of Jinja2Cpp build in order to collect all necessary headers and libs in one place. Like in this file: https://github.com/jinja2cpp/examples-build/blob/master/external/internal/build.bat

**Comment by Alex-Tsvetanov** [comment]
I have MinGW's path put in PATH and I'm able to use just ``gcc.exe`` and ``g++.exe`` without any mentions of theirs paths.

The problem with this ``.bat`` is that there is no mention of c++17, so should I change CXX_STANDARD to 17 from 14 in CMakeFiles.txt?

**Comment by flexferrum** [comment]
> The problem with this .bat is that there is no mention of c++17, so should I change CXX_STANDARD to 17 from 14 in CMakeFiles.txt?

It's possible to put it in the cmake command line. Like this:
```
cmake ..\ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\.jinja2cpp-install -DJINJA2CPP_BUILD_TESTS=OFF -DJINJA2CPP_DEPS_MODE=internal -DJINJA2CPP_CXX_STANDARD=17
```
(see the last param)

**Comment by Alex-Tsvetanov** [comment]
This time there was no errors. So how should I link the library?

```
Install the project...
-- Install configuration: "Release"
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/nonstd/expected.hpp
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/nonstd/variant.hpp
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/nonstd/optional.hpp
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/nonstd/string_view.hpp
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib/static/libjinja2cpp.a
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/nlohmann_json.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/rapid_json.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/error_handler.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/error_info.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/filesystem_handler.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/generic_list.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/generic_list_impl.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/generic_list_iterator.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/reflected_value.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/string_helpers.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/template.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/template_env.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/user_callable.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/value.h
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include/jinja2cpp/value_ptr.hpp
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/share/pkgconfig/jinja2cpp.pc
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib/jinja2cpp/jinja2cpp-cfg.cmake
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib/jinja2cpp/jinja2cpp-cfg-release.cmake
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib/jinja2cpp/jinja2cpp-config.cmake
-- Installing: D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib/jinja2cpp/jinja2cpp-config-deps.cmake
```

**Comment by flexferrum** [comment]
> So how should I link the library?

- Add path to `D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/include` to include dirs list
- Add path to `D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib` to library dirs list
- Add `jinja2cpp` to the libraries list
- Add these defines: `variant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD`, `nssv_CONFIG_SELECT_STRING_VIEW=nssv_STRING_VIEW_NONSTD`, `optional_CONFIG_SELECT_OPTIONAL=optional_OPTIONAL_NONSTD`, `BOOST_SYSTEM_NO_DEPRECATED`, `BOOST_ERROR_CODE_HEADER_ONLY` to the compiler options

**Comment by Alex-Tsvetanov** [comment]
Well, almost there:
with ``-ljinja2cpp``:
```atsve@DESKTOP-9NG9NPT MINGW64 /d/Users/atsve/OneDrive/Documents/GitHub/WebFrame (master)
$ make
g++.exe --std=c++17 -O3 -Ofast ./src/main.cpp -o ./bin/main.exe -I./tests -I./src -I./lib/win/mingw-std-threads-master -I./lib/win/filesystem-master/include/ -I./lib/win/stopwatch/  -Wall -Wno-long-long -pedantic -fconcepts -lwsock32 -lws2_32 -static -I./lib/Jinja2Cpp/.jinja2cpp-install/include -L./lib/Jinja2Cpp/.jinja2cpp-install/lib -ljinja2cpp  -Dvariant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -Dnssv_CONFIG_SELECT_STRING_VIEW=nssv_STRING_VIEW_NONSTD -Doptional_CONFIG_SELECT_OPTIONAL=optional_OPTIONAL_NONSTD -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-sjlj-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ljinja2cpp
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:12: build] Error 1
```

without ``-ljinja2cpp``:
```
atsve@DESKTOP-9NG9NPT MINGW64 /d/Users/atsve/OneDrive/Documents/GitHub/WebFrame (master)
$ make
g++.exe --std=c++17 -O3 -Ofast ./src/main.cpp -o ./bin/main.exe -I./tests -I./src -I./lib/win/mingw-std-threads-master -I./lib/win/filesystem-master/include/ -I./lib/win/stopwatch/  -Wall -Wno-long-long -pedantic -fconcepts -lwsock32 -lws2_32 -static -I./lib/Jinja2Cpp/.jinja2cpp-install/include -L./lib/Jinja2Cpp/.jinja2cpp-install/lib -Dvariant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -Dnssv_CONFIG_SELECT_STRING_VIEW=nssv_STRING_VIEW_NONSTD -Doptional_CONFIG_SELECT_OPTIONAL=optional_OPTIONAL_NONSTD -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY
C:\Users\atsve\AppData\Local\Temp\ccyLJ9Lq.o:main.cpp:(.text+0x25fc): undefined reference to `jinja2::Template::LoadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
C:\Users\atsve\AppData\Local\Temp\ccyLJ9Lq.o:main.cpp:(.text+0x2631): undefined reference to `jinja2::Template::RenderAsString(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, jinja2::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, jinja2::Value> > > const&)'
C:\Users\atsve\AppData\Local\Temp\ccyLJ9Lq.o:main.cpp:(.text$_ZN8webnetpp8webnetppC1Ev[_ZN8webnetpp8webnetppC1Ev]+0x148): undefined reference to `jinja2::Template::Template(jinja2::TemplateEnv*)'
C:\Users\atsve\AppData\Local\Temp\ccyLJ9Lq.o:main.cpp:(.text$_ZN8webnetpp8webnetppD1Ev[_ZN8webnetpp8webnetppD1Ev]+0x41): undefined reference to `jinja2::Template::~Template()'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:12: build] Error 1
```

**Comment by Alex-Tsvetanov** [comment]
Never mind, it works with 
- Add path to ``D:/Users/atsve/OneDrive/Documents/GitHub/WebFrame/lib/Jinja2Cpp/.jinja2cpp-install/lib``**/static** to library dirs list

Thanks for your support, @flexferrum! 😄

**Comment by flexferrum** [comment]
You are welcome. :)
