### ISSUE TITLE
Jinja2cpp with external-boost doesn't work on gcc 

### ISSUE THREAD

**Issue by ludekvodicka** [jinja2cpp/Jinja2Cpp#189]
Hi,

now I'm trying to compile jinja2cpp on Linux, also with external boost library (1.7.0)

`cmake ../ -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST_PATH -DJINJA2CPP_BUILD_TESTS="OFF" -DJINJA2CPP_DEPS_MODE=external-boost -DBoost_INCLUDE_DIR=/root/dev/SharedLibraries/boost/include`

or

`cmake ../ -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST_PATH -DJINJA2CPP_BUILD_TESTS="OFF" -DJINJA2CPP_DEPS_MODE=external-boost -DBOOST_ROOT=/root/dev/SharedLibraries/boost/include`

or

`export BOOST_ROOT=/root/dev/SharedLibraries/boost/include`
`cmake ../ -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST_PATH -DJINJA2CPP_BUILD_TESTS="OFF" -DJINJA2CPP_DEPS_MODE=external-boost`

And although boost 1.7.0 works on Windows  (with the same cmake settings), on Linux there is some error:

```
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 107000
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  thirdparty/external_boost_deps.cmake:29 (find_package)
  thirdparty/thirdparty-external-boost.cmake:4 (include)
  thirdparty/CMakeLists.txt:43 (include)
  CMakeLists.txt:150 (include)

CMake Error at CMakeLists.txt:120 (add_library):
  Target "jinja2cpp" links to target "Boost::boost" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

and althought this is warning only, jinja2cpp compilation crashed:

```
Scanning dependencies of target jinja2cpp
[  5%] Building CXX object CMakeFiles/jinja2cpp.dir/src/error_info.cpp.o
[ 11%] Building CXX object CMakeFiles/jinja2cpp.dir/src/expression_evaluator.cpp.o
In file included from /root/dev/ExternalLibraries/jinja2/src/expression_evaluator.h:4:0,
                 from /root/dev/ExternalLibraries/jinja2/src/expression_evaluator.cpp:1:
/root/dev/ExternalLibraries/jinja2/src/internal_value.h:6:10: fatal error: boost/iterator/iterator_facade.hpp: No such file or directory
 #include <boost/iterator/iterator_facade.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Path /root/dev/SharedLibraries/boost/include is valid as same as file boost/iterator/iterator_facade.hpp exists in this directory.

Everything works fine with internal mode `-DJINJA2CPP_DEPS_MODE=internal`

`cmake ../ -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST_PATH -DJINJA2CPP_BUILD_TESTS="OFF" -DJINJA2CPP_DEPS_MODE=internal`

Do you have any ideas what can cause that? Thanks

**Comment by ludekvodicka** [comment]
When I removed "QUIET" flag in cmake:

```
find_package(boost_filesystem )
find_package(boost_algorithm  )
find_package(boost_variant    )
find_package(boost_optional   )
```

I received this error

```
CMake Warning at thirdparty/external_boost_deps.cmake:1 (find_package):
  By not providing "Findboost_filesystem.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "boost_filesystem", but CMake did not find one.

  Could not find a package configuration file provided by "boost_filesystem"
  with any of the following names:

    boost_filesystemConfig.cmake
    boost_filesystem-config.cmake

  Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
  set "boost_filesystem_DIR" to a directory containing one of the above
  files.  If "boost_filesystem" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  thirdparty/thirdparty-external-boost.cmake:4 (include)
  thirdparty/CMakeLists.txt:43 (include)
  CMakeLists.txt:150 (include)
```

But there is no such *.cmake file in installed boost folder (boost is compiled from source).

Unfortunately, I'm not sure how to fix that. We're using qmake system and I'm not very familiar with cmake.Thanks

**Comment by ludekvodicka** [comment]
It seems that similar warnings about invalid boost path I have also on windows platform. But the compilation works there. So the issue is probably somewhere else.

I'm still trying to find a reason why compilation didn't find boost paths.

**Comment by ludekvodicka** [comment]
I have probably found temporary solution. It seems that in case of external-boost mode jinja2cpp doesn't add passed boost paths to build system

I'm able to compile it in case I add these paths manually via CMAKE_CXX_FLAGS flags :

`cmake ../ -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$DEST_PATH -DJINJA2CPP_BUILD_TESTS="OFF" -DJINJA2CPP_DEPS_MODE=external-boost -DCMAKE_CXX_FLAGS=-isystem\ $SHL_PATH/boost/include`

**Comment by ludekvodicka** [comment]
I have another error during linking process:

/usr/bin/ld: /root/dev/SharedLibraries/jinja2cpp/lib/static/libjinja2cpp.a(error_info.cpp.o): relocation R_X86_64_32 against `_ZN3fmt2v512format_errorD1Ev' can not be used when making a shared object; recompile with -fPIC
/root/dev/SharedLibraries/jinja2cpp/lib/static/libjinja2cpp.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Here is more info about this issue: https://stackoverflow.com/questions/19364969/compilation-fails-with-relocation-r-x86-64-32-against-rodata-str1-8-can-not/42388145

It seems that libjinja2cpp have to be compiled with -fPIC flag on gcc

**Comment by flexferrum** [comment]
Thanks for trying it out.

Regarding to `-fPIC` - thats my fault. I'll add it ASAP.

Regarding to boost package find. In case of `external-boost` and `external` modes Jinja2Cpp CMake script uses standard boost finder. And this finder has got some... hmm... picularities:

- You should specify path to the boost installation via `BOOST_ROOT` or `BOOSTROOT` CMake variable:

> 
> This module reads hints about search locations from variables:
> 
> **BOOST_ROOT             - Preferred installation prefix
>  (or BOOSTROOT)**
> BOOST_INCLUDEDIR       - Preferred include directory e.g. <prefix>/include
> BOOST_LIBRARYDIR       - Preferred library directory e.g. <prefix>/lib
> Boost_NO_SYSTEM_PATHS  - Set to ON to disable searching in locations not
>                          specified by these hint variables. Default is OFF.
> Boost_ADDITIONAL_VERSIONS
>                        - List of Boost versions not known to this module
>                          (Boost install locations may contain the version)
> and saves search results persistently in CMake cache entries:
> 
https://cmake.org/cmake/help/v3.15/module/FindBoost.html

- For some  versions of `boost` old CMake finders could work improperly.

**Comment by ludekvodicka** [comment]
Fix -fPIC works great. I'm now able to compile the application with GCC.

Regarding boost, I also tried BOOST_ROOT but this doesn't help. I have Ubuntu 16.04 together with CMake 3.5.2 in our docker dev machines.  I'm going to try to update it and let you know.

**Comment by ludekvodicka** [comment]
Updating to CMake 3.13.4 fixed the issue. So the problem was probably caused by 3.5.2 version.

Here are steps I used to update to Cmake 3.13.4 on Ubuntu 16.04 and 18.04 in our docker machines:

```
#cmake
RUN apt purge cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz
RUN tar -zxvf cmake-3.13.4.tar.gz
WORKDIR "/cmake-3.13.4"
RUN ./bootstrap
RUN make
RUN make install
RUN ln -s /usr/local/bin/cmake /usr/bin/cmake
```
