### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by luismartingil** [jinja2cpp/Jinja2Cpp#215]
@rmorozov 

- Latest Release [1.1.0](https://github.com/jinja2cpp/Jinja2Cpp/releases) is dated Jan, 2020
- Do you think we could make an official release for 1.2.0? We'll try that RC to make it to [Conan Center too](https://conan.io/center/jinja2cpp)...

FYI @danielmartinezruiz @league55

**Comment by rmorozov** [comment]
Hello, @luismartingil!

As I see you would like to have release to Conan to be able to use jinja2cpp with new deps?

Anything else we need to include into this release except closing current PR's and maybe one-two bugs?

**Comment by luismartingil** [comment]
Hello @rmorozov - thanks for the quick response!

Our concerns would be:
1. Adding [this PR](https://github.com/jinja2cpp/Jinja2Cpp/pull/214) into the Release
2. Making it available in Conan Center

Can we assist you anyhow?

**Comment by rmorozov** [comment]
1. Sure I've started CI as soon as it completes I'll merge it.

2. I am not quite familiar with a process of publication to Conan center - and that's a place where a help could be beneficial

But let's move sequentially - release, then publication.

**Comment by rmorozov** [comment]
It seems that fix of https://github.com/jinja2cpp/Jinja2Cpp/issues/213 is also good candidate for release

**Comment by luismartingil** [comment]
@rmorozov I answered in [issue 213](https://github.com/jinja2cpp/Jinja2Cpp/issues/213) - I don't think Clang-12 is officially supported at this time...

**Comment by luismartingil** [comment]
@rmorozov We're currently looking at this (@league55 FYI)

**Comment by league55** [comment]
Looks good to me.  I wasn't able to test it within our product, but the build, unit tests, and release content look good to me.
So, no blockers for final release from our side @rmorozov 

@luismartingil fyi.

**Comment by luismartingil** [comment]
@rmorozov Good to go for us!

**Comment by luismartingil** [comment]
@rmorozov You're working on the latest details before the release, right?

**Comment by rmorozov** [comment]
@luismartingil , as far as I understand know we need to make a PR to Conan-center-index?

**Comment by luismartingil** [comment]
@rmorozov Right - [here](https://github.com/conan-io/conan-center-index/tree/master/recipes/jinja2cpp) - we'll add it there

**Comment by luismartingil** [comment]
@rmorozov FYI [here](https://github.com/conan-io/conan-center-index/pull/7147)

**Comment by luismartingil** [comment]
@rmorozov Available in Conan now... thanks! https://github.com/conan-io/conan-center-index/pull/7147
