### ISSUE TITLE
Add boost::json as an alternative to rapidjson

### ISSUE THREAD

**Issue by eklitzke** [jinja2cpp/Jinja2Cpp#223]
This is a feature request to add [boost::json](https://www.boost.org/doc/libs/develop/libs/json/doc/html/index.html) as an alternative to rapidjson/nlohmann. The boost::json API is actually quite similar to rapidjson, in many cases the code is the same but the method names are snake-case like `.is_array()` instead of camel-case like rapidjson's `.IsArray()`.

Also it would be nice to be able to build Jinja2Cpp without any JSON support at all.

**Comment by rmorozov** [comment]
I've added some support to boost::json. I don't think it is good idea to build jinja2cpp without json support - because there is some filters in jinj2 spec. But some more fine-grained configuration is a good idea.
