### ISSUE TITLE
Needs boost-1.80.0 to build on gcc12

### ISSUE THREAD

**Issue by sdegrande** [jinja2cpp/Jinja2Cpp#230]
std::unary_function is now marked as deprecated with gcc12 in C++17 mode, preventing boost::container_hash to build.
It has been fixed in boost-1.80.0, see https://github.com/boostorg/config/commit/89ff6355e15f0d1b1ecfcf863c123483ab331957

So, please, update the boost dependency.

Thanks for your work !

**Comment by rmorozov** [comment]
It seems that this commit is in 1.81 work tree. At this moment I see only option to suppress deprecated warnings.

But yes I've updated boost dep to 1.80

**Comment by sdegrande** [comment]
Thanks !
