### ISSUE TITLE
fatal error: jinja2cpp/utils/i_comparable.h: No such file or directory

### ISSUE THREAD

**Issue by sdegrande** [jinja2cpp/Jinja2Cpp#233]
Latest version (94636707), build on Linux (Fedora 37), and installed with 'make install/local'.

When I then build my code which uses Jinja2cpp, i got an error:

/usr/local/include/jinja2cpp/generic_list.h:4:10: fatal error: jinja2cpp/utils/i_comparable.h: No such file or directory

Indeed, all the headers from the include/jinja2cpp subdirs are installed into /usr/local/include/jinja2cpp (without copying the subdir hierarchy).

I do not have enough knowledge of CMake to propose a patch, sorry, but it comes from the definition of PUBLIC_HEADER in the main CMakeLists.txt

Thanks for your work !

**Comment by rmorozov** [comment]
@sdegrande , I've tried to fix it, would you mind checking it on your configuration?

need to invent some special check on CI for this kind of issue

**Comment by sdegrande** [comment]
It now installs correctly, copying the include/ structure. Thx !

I now have to update my code to the jinja2cpp changes (introduction of Interface classes...).
BTW, FYI, I bind  jinja2cpp to JsonCpp (or is it the way around ? :-))

**Comment by sdegrande** [comment]
The update was easy. Given that the JsonCpp binding is quite similar to Nlohmann's one, I just had to apply the same changes (potentially, if you would like to add it upstream, I could propose a pull request)

Everything works as expected.

Thx again for your work !
