### ISSUE TITLE
cmake file not properly nested

### ISSUE THREAD

**Issue by mberntsen** [jinja2cpp/Jinja2Cpp#238]
cmake/public/jinja2cpp-config.cmake.in

line 62:

if (JINJA2CPP_BUILD_SHARED)
    target_compile_definitions(jinja2cpp PUBLIC -DJINJA2CPP_LINK_AS_SHARED)
else()

should the 'else' be an 'endif'?

**Comment by sdegrande** [comment]
Yes, it should...

**Comment by sdegrande** [comment]
Thanks a lot
