### ISSUE TITLE
PSA: Consider using Rust MiniJinja crate instead of Jinja2Cpp

### ISSUE THREAD

**Issue by tjsmith-meta** [jinja2cpp/Jinja2Cpp#269]
If you're in C++ land, then it may not be too hard for you to leverage the MiniJinja crate, where cxx.rs provides a nice and easy way to call Rust code from C++.
https://cxx.rs/

Rust MiniJinja has the following advantages over Jinja2Cpp (in my anecdotal experience).
1. Far fewer bugs / crashes / matches the official Jinja2 spec much more closely.
2. Decent bit more performant (YMMV).
3. Appears to be more actively developed / maintained.

**Comment by rmorozov** [comment]
hello @tjsmith-meta

I think that choosing dependency for your project is always about your own calculations of pros and cons.

I' ll try to assume some decision tree
- your project is hobby or commercial
  - if you choose for your hobby project just take anything you like at the moment
  - for commercial project
    - if it's startup project
      - i would go for familiar technologies to be as fast as possible to deliver first mvp
    - if it's mature project
      - consider build reproducibility 
      - consider availability of at least two guys on project who eager to support rust toolchain
      - consider project sustainability - would you switch to rust completely in future 
      - level of maintenance is dramatically changing factor
      - lots of factors more😁

If you have some specific questions feel free to reopen issue
