### ISSUE TITLE
Implement 'import' statement

### ISSUE THREAD

**Issue by flexferrum** [jinja2cpp/Jinja2Cpp#42]
Implement 'import' statement according to specification: http://jinja.pocoo.org/docs/2.10/templates/#import

**Comment by Manu343726** [comment]
It seems that my workaround, extending a main template with macro definitions and referencing that macros in the extended block of the child didn't work.

What's the state of this feature?

BTW let me thank you for all your work.

**Comment by flexferrum** [comment]
Try to mark block as 'scoped". By default all parent definitions are hidden in child block content.

**Comment by Manu343726** [comment]
I've written a simple test to check if I'm doing things right. Of course it's failing. https://gitlab.com/Manu343726/tinyrefl/-/jobs/104347470 (tinyrefl-tool-test).

See https://github.com/Manu343726/tinyrefl/blob/jinja2-based-tool/tool/tests/templates/macro_based_codegen/model.cpp#L126

Two of these tests fail:

 - `simple_test(
        "{{file.classes|map('name')|join(',')}}", "Base,Class,Tag,AnotherTag");`
 - `test(
        "{{include_guard(file)}}",
        "TINYREFL_TOOL_GENERATED_" +
            boost::algorithm::replace_all_copy(
                std::string{TINYREFL_TOOL_SOURCE_DIR "/tests/class.hpp"},
                "/",
                "_") +
            "_INCLUDED");`

*`test()` runs the test using a template extensing my `model.jinja2` template, the passed template being written in the body of a `body` scoped block. `simple_test()` just runs the given template.

**Comment by flexferrum** [comment]
Hm... I see. OK. About the first case. Expression you wrote is trying to apply filter `name` to every list item. In order to select attribute `name` you should write explicitly: `map(attribute='name')` Let's say "thanks" together to the authors of Jinja2 spec. :) About the second case (with macro from the base template) I have to check. Now it looks like my fault.

**Comment by flexferrum** [comment]
> I have to check. Now it looks like my fault.

No. jinja2Cpp works as expected and all macros from the parent template are visible. I've investigated your commit:
https://github.com/Manu343726/tinyrefl/commit/dc3182f4403ae00dd654affe6f534accfc9e30e1
and found the problem: you don't initialize the template environment. In case of 'extends'/'block' statements usage that's is crucial. I'll make some comments in your commit.

**Comment by flexferrum** [comment]
https://github.com/jinja2cpp/Jinja2Cpp/commit/d1d2b04117062212b07b20cec45e1a81f0b18286
