### ISSUE TITLE
Testing and Development of Support for Clang and GCC on Windows

### ISSUE THREAD

**Issue by DragonOsman** [jinja2cpp/Jinja2Cpp#79]
This is a feature request.  If possible, I'd like to ask for testing and development of build support for LLVM Clang and GCC on Windows, in case issues like mine with VS2017 come up.

**Comment by flexferrum** [comment]
That's not in the nearest plans.

**Comment by DragonOsman** [comment]
To add to this, it'd be good if we had support for building Jinja2Cpp with LLVM as a toolset for VS2017, for when someone has a project using Jinja2Cpp that they want to port to WebAssembly (since WebAssembly is built using LLVM (the Emscripten toolchain uses an LLVM backend)).
