### ISSUE TITLE
[thirdparty] Rename *-light to *-lite

### ISSUE THREAD

**Issue by martinmoene** [jinja2cpp/Jinja2Cpp#94]
In `Jinja2Cpp/thirdparty/nonstd/CMakeLists.txt`:
- line 7: ${CMAKE_CURRENT_SOURCE_DIR}/expected-**light**/include|
- line 8: ${CMAKE_CURRENT_SOURCE_DIR}/variant-**light**/include|
- line 14: ${CMAKE_CURRENT_SOURCE_DIR}/expected-**light**/include/nonstd/expected.hpp|
- line 15: ${CMAKE_CURRENT_SOURCE_DIR}/variant-**light**/include/nonstd/variant.hpp|

`s/light/lite/g`

Related to #82

**Comment by flexferrum** [comment]
Actually, this file has to be removed. It's unused since integration with conan.io.

**Comment by flexferrum** [comment]
#102
